### ISSUE TITLE
[doc] Explain mutation testing

### ISSUE THREAD

**Issue by Guekka** [RagnarDa/dumbmutate#3]
Came here from Reddit post. I had no idea what was mutation testing until I found this repo.
It would be nice if you could add some resources, explaining what is mutation testing and why use it. At least a link to a blog post, for example
Edit: just noticed someone already asked that on Reddit. Well, now there's an issue to track progress :p

**Comment by RagnarDa** [comment]
Thanks for feedback! Added explanation. If there is more info needed or something is unclear, please let me know.
