### ISSUE TITLE
Can it used in cmake?

### ISSUE THREAD

**Issue by foobra** [RagnarDa/dumbmutate#5]
for use of automatic use in daily ci job

**Comment by RagnarDa** [comment]
There's no integration with CMake specifically if that is what you mean, but if you project builds via CMake you could just do --build="cmake --build ." in the command line.

If you want mutation-test all files that are changed in a commit you can make a script like this:
`for s in `git show --pretty="" --name-only master`; do dumbmutate --build=make --test=runtest --mutate=$s; done` Be aware that mutation testing takes a lot of time and also makes lots of writes to the harddrive so might want to make a RAM-drive for this.
