### ISSUE TITLE
How to run your demo as your gif did?

### ISSUE THREAD

**Issue by ShowyoumyCannon** [RagnarDa/dumbmutate#7]
I'm sorry to bother you. I just start to learn mutate test and really unfamiliar to testing framework.
I download your project and just did what you did as gif. I found it was different between you gif 's main.cpp and your demo's main.cpp .So I change the file by using TEST_CASE and doctest .Then I found that the file failed to compile.
 error message like this:
Undefined symbols for architecture x86_64:
  "doctest_detail_test_suite_ns::getCurrentTestSuite()", referenced from:
      ___cxx_global_var_init.5 in main-6b9dae.o
  "doctest::getContextOptions()", referenced from:
      doctest::detail::Result doctest::detail::Expression_lhs<int const&>::operator==<int>(int const&) in main-6b9dae.o
      doctest::detail::Result doctest::detail::Expression_lhs<int const&>::operator!=<int>(int const&) in main-6b9dae.o
......
can you help me? It must have something wrong about doctest using. I use macos system. 
I knew it is really a low level issue. But I really want to learn and run your project. Thank you!

**Comment by RagnarDa** [comment]
Glad you figured it and good of you to post the solution!
